# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07f8e9ab22d588a78bae5edccd17c95ccbe7a2b2974eb0ee6703d05cf5eab2044ecef700782fb8c4919ff237af89448006512fd1451c3925662893a5ca51547e

test:
  secret_key_base: 2509614bd44841fa41789aa69446ea8d8d96f1f8f30814284e46673b2d4832ad4b789e7ca0958db3cc0ba0f0c08a429fa8d78a1d7179181fc32ca297fb18b7f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
